CREATE DATABASE db_311ci;

CREATE TABLE USER_ACTION_LOG(
    USER_ACTION_LOG_ID SERIAL PRIMARY KEY,
    LOGIN_STAMP TIMESTAMP NOT NULL
);

CREATE TABLE REGISTERED_USER(
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    USER_ACTION_LOG_ID SERIAL NOT NULL,
    FOREIGN KEY (USER_ACTION_LOG_ID)
        REFERENCES USER_ACTION_LOG(USER_ACTION_LOG_ID)
);

CREATE TABLE REQUEST_TYPE(
    REQUEST_ID SERIAL PRIMARY KEY,
    TYPE_OF_SERVICE_REQUEST SERIAL UNIQUE NOT NULL,
    NAME VARCHAR(42) NOT NULL
);

CREATE TABLE EXTRA_INCIDENT_INFO(
    EXTRA_INCIDENT_INFO_ID SERIAL PRIMARY KEY,
    INCIDENT_ID SERIAL UNIQUE NOT NULL,
    HISTORICAL_WARDS_2003_2015 INTEGER,
    ZIP_CODES INTEGER,
    COMMUNITY_AREAS INTEGER,
    CENSUS_TRACKS INTEGER,
    WARDS INTEGER
);

CREATE TABLE DISTRICT(
    DISTRICT_ID SERIAL PRIMARY KEY,
    ZIP_CODE INTEGER,
    WARD INTEGER,
    POLICE_DISTRICT INTEGER,
    COMMUNITY_AREA INTEGER
);

CREATE TABLE STATUS_TYPE(
    STATUS_TYPE_ID SERIAL PRIMARY KEY,
    STATUS_TYPE_NAME VARCHAR(42)
);

CREATE TABLE INCIDENT(
    INCIDENT_ID SERIAL PRIMARY KEY,
    USER_ID SERIAL UNIQUE,
    CREATION_DATE DATE NOT NULL,
    STATUS_TYPE_ID SERIAL NOT NULL,
    COMPLETION_DATE DATE,
    SERVICE_REQUEST_NUMBER INTEGER UNIQUE NOT NULL,
    TYPE_OF_SERVICE_REQUEST SERIAL NOT NULL,
    STREET_ADDRESS VARCHAR(42),
    LONGTITUDE FLOAT UNIQUE,
    LATITUDE FLOAT UNIQUE,
    X_COORDINATE FLOAT,
    Y_COORDINATE FLOAT,
    EXTRA_INCIDENT_INFO_ID SERIAL,
    DISTRICT_ID SERIAL,
    FOREIGN KEY (USER_ID)
        REFERENCES REGISTERED_USER(USER_ID),
    FOREIGN KEY (TYPE_OF_SERVICE_REQUEST)
        REFERENCES REQUEST_TYPE(TYPE_OF_SERVICE_REQUEST),
    FOREIGN KEY (DISTRICT_ID)
        REFERENCES DISTRICT(DISTRICT_ID),
    FOREIGN KEY (EXTRA_INCIDENT_INFO_ID)
        REFERENCES EXTRA_INCIDENT_INFO(EXTRA_INCIDENT_INFO_ID),
    FOREIGN KEY (STATUS_TYPE_ID)
        REFERENCES STATUS_TYPE(STATUS_TYPE_ID)
);

CREATE TABLE SSA(
    SSA_ID SERIAL PRIMARY KEY,
    SSA INTEGER
);

CREATE TABLE ABANDONED_VEHICLE(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    SSA_ID SERIAL,
    LICENSE_PLATE VARCHAR(42),
    VEHICLE_MAKE_MODEL VARCHAR(42),
    VEHICLE_COLOR VARCHAR(42),
    CURRENT_ACTIVITY VARCHAR(120),
    MOST_RECENT_ACTION VARCHAR(120),
    DAYS_REPORTED_PARKED INTEGER,
    FOREIGN KEY (REQUEST_ID)
        REFERENCES REQUEST_TYPE(REQUEST_ID),
    FOREIGN KEY (SSA_ID)
        REFERENCES SSA(SSA_ID)
);

CREATE TABLE ALLEY_LIGHTS_OUT(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    FOREIGN KEY (REQUEST_ID)
        REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE GARBAGE_CARTS(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    DELIVERED_BLACK_CARTS_NUM INTEGER,
    CURRENT_ACTIVITY VARCHAR(120),
    MOST_RECENT_ACTION VARCHAR(120),
    SSA_ID SERIAL,
    FOREIGN KEY (REQUEST_ID)
      REFERENCES REQUEST_TYPE(REQUEST_ID),
    FOREIGN KEY (SSA_ID)
        REFERENCES SSA(SSA_ID)
);

CREATE TABLE GRAFFITI_REMOVAL(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    SURFACE_TYPE VARCHAR(120),
    GRAFFITI_LOCATION VARCHAR(120),
    SSA_ID SERIAL,
    FOREIGN KEY (REQUEST_ID)
        REFERENCES REQUEST_TYPE(REQUEST_ID),
    FOREIGN KEY (SSA_ID)
        REFERENCES SSA(SSA_ID)
);

CREATE TABLE POT_HOLES_REPORTED(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    CURRENT_ACTIVITY VARCHAR(120),
    MOST_RECENT_ACTION VARCHAR(120),
    FILLED_BLOCK_POTHOLES_NUM INTEGER,
    SSA_ID SERIAL,
    FOREIGN KEY (REQUEST_ID)
       REFERENCES REQUEST_TYPE(REQUEST_ID),
    FOREIGN KEY (SSA_ID)
        REFERENCES SSA(SSA_ID)
);

CREATE TABLE RODENT_BATING(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    BAITED_PREMISES_NUM INTEGER,
    PREMISES_WITH_GARBAGE_NUM INTEGER,
    PREMISES_WITH_RATS_NUM INTEGER,
    CURRENT_ACTIVITY VARCHAR(120),
    MOST_RECENT_ACTION VARCHAR(120),
    FOREIGN KEY (REQUEST_ID)
      REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE SANITATION_CODE_COMPLAINTS(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    VIOLATION_NATURE VARCHAR(120),
    FOREIGN KEY (REQUEST_ID)
       REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE STREET_LIGHTS_ALL_OUT(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    FOREIGN KEY (REQUEST_ID)
      REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE STREET_LIGHTS_ONE_OUT(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    FOREIGN KEY (REQUEST_ID)
      REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE TREE_DEBRIS(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    DEBRIS_LOCATION VARCHAR(120),
    CURRENT_ACTIVITY VARCHAR(120),
    MOST_RECENT_ACTION VARCHAR(120),
    FOREIGN KEY (REQUEST_ID)
        REFERENCES REQUEST_TYPE(REQUEST_ID)
);

CREATE TABLE TREE_TRIMS(
    ID SERIAL PRIMARY KEY,
    REQUEST_ID SERIAL NOT NULL,
    TREE_LOCATION VARCHAR(120),
    FOREIGN KEY (REQUEST_ID)
       REFERENCES REQUEST_TYPE(REQUEST_ID)
);
